services:
  - type: web
    name: bot-galicia-n4-web
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
